name: build-angle

on:
  workflow_call:
    inputs:
      ignore-cache:
        required: false
        type: string
        default: false
      config:
        description: 'Controls building in release or debug'
        required: false
        type: string
        default: 'release'
  workflow_dispatch:
    inputs:
      ignore-cache:
        required: false
        type: string
        default: false
      config:
        description: 'Controls building in release or debug'
        required: false
        type: string
        default: 'release'

jobs:
  build-win:
    runs-on: windows-2022
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: actions/checkout@v4

      - name: Angle version
        id: angle-version
        shell: cmd
        run: |
          @chcp 65001>nul
          set /p ANGLE_COMMIT=<commit.txt
          echo ANGLE_COMMIT=%ANGLE_COMMIT% >> %GITHUB_OUTPUT%

      - name: Cache
        id: cache-angle
        uses: actions/cache@v3
        if: inputs.ignore-cache != 'true'
        with:
          key: angle-${{ runner.os }}-${{ runner.arch }}-${{ steps.angle-version.outputs.ANGLE_COMMIT }}-${{ inputs.config }}
          path: build/angle.out

      - name: Build Angle
        if: steps.cache-angle.outputs.cache-hit != 'true' || inputs.ignore-cache == 'true'
        run: python build.py --config=${{ inputs.config }}

      - uses: actions/upload-artifact@v4
        with:
          name: angle-windows-x64
          path: build/angle.out

  build-macos:
    strategy:
      matrix:
        os: [macos-14, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: actions/checkout@v4

      - name: Angle version
        id: angle-version
        run: |
          echo "ANGLE_COMMIT=$(cat commit.txt)" >> $GITHUB_OUTPUT
          ARCH=${{ runner.arch }}
          echo "LOWERCASE_ARCH=$(echo $ARCH | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Cache
        id: cache-angle
        uses: actions/cache@v3
        if: inputs.ignore-cache != 'true'
        with:
          key: angle-${{ runner.os }}-${{ runner.arch }}-${{ steps.angle-version.outputs.ANGLE_COMMIT }}-${{ inputs.config }}
          path: build/angle.out

      - name: Build Angle
        if: steps.cache-angle.outputs.cache-hit != 'true' || inputs.ignore-cache == 'true'
        run: python build.py

      - uses: actions/upload-artifact@v4
        with:
          name: angle-mac-${{steps.angle-version.outputs.LOWERCASE_ARCH}}
          path: build/angle.out
